### ISSUE TITLE
Where are all the SASS files stored?

### ISSUE THREAD

**Issue by raghav-kukreti** [franklintiel/django2-semantic-ui#1]
I just installed this using pipenv and it's retrieving the minified CSS and js.
I cannot understand how to edit the variables and the individual components.
Where are they stored exactly?

**Comment by franklintiel** [comment]
Hi brother, the SASS files are stored on the static folder, you need
download the staticfiles firest using the command "python manage.py
collectstatic",  in this moment I could not complete the module to allow
build a custom theme, but,  you could to access to SASS files using the
"collectstatic" command

I'm so sorry for this I will be working on the next days on this features

Let me know about it.

Good luck and thanks for you support

____________________________________________________
*Franklin Sarmiento*
*Full-stack developer*
*skype: franklin.s.dev*
*Twitter: @franklinitiel*
*linkedin: Franklin Sarmiento ( franklinitiel@gmail.com
<franklinitiel@gmail.com> )*
*E-mail: franklinitiel@gmail.com <franklinitiel@gmail.com>*
*Teléfono(s): +57 321 2287421 / +57 320 490.79.64 ( whatsapp )*

**Comment by raghav-kukreti** [comment]
Alright mate.
Thanks for the great project!

**Comment by franklintiel** [comment]
Hola,

Acabo de firmar la petición de "United Nations: Expel Maduro from the Human
Rights Council!" y me encantaría que me ayudaras sumando tu firma.

Nuestro objetivo es llegar a 150,000 firmas y necesitamos más apoyo. Para
obtener más información y firmar la petición puedes abrir el siguiente link:

http://chng.it/GpgXc5d9WW

¡Gracias!
Franklin
